"""
FastAPI Server for CrewAI Agents
Generated by: CrewAI Learning Archive
Date: June 12, 2026
Purpose: Make agents accessible via HTTP REST API
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from crewai import Agent, Task, Crew
from crewai.llm import LLM
from dotenv import load_dotenv
from datetime import datetime
import uvicorn

load_dotenv()

# ============================================================
# INITIALIZE FASTAPI APP
# ============================================================

app = FastAPI(
    title="CrewAI Agent API",
    description="REST API for multi-agent AI system",
    version="1.0.0"
)

# Enable CORS (allows requests from anywhere)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================================
# INITIALIZE LLM
# ============================================================

llm = LLM(model="ollama/mistral", base_url="http://localhost:11434")

# ============================================================
# REQUEST & RESPONSE MODELS
# ============================================================

class GenerateBlogRequest(BaseModel):
    """Request model for blog generation"""
    topic: str
    length: str = "medium"  # short, medium, long

class GenerateBlogResponse(BaseModel):
    """Response model for blog generation"""
    status: str
    topic: str
    blog_post: str
    generated_at: str


class AnalyzeDataRequest(BaseModel):
    """Request model for data analysis"""
    data: str
    data_type: str = "sales"  # sales, traffic, engagement, etc.

class AnalyzeDataResponse(BaseModel):
    """Response model for data analysis"""
    status: str
    analysis: str
    insights: list
    generated_at: str


class ReviewCodeRequest(BaseModel):
    """Request model for code review"""
    code: str
    language: str = "python"  # python, javascript, java, etc.

class ReviewCodeResponse(BaseModel):
    """Response model for code review"""
    status: str
    review: str
    issues_found: int
    suggestions: list
    generated_at: str


class HealthResponse(BaseModel):
    """Health check response"""
    status: str
    message: str
    timestamp: str

# ============================================================
# AGENTS
# ============================================================

blog_writer = Agent(
    role="Professional Blog Writer",
    goal="Write engaging, SEO-optimized blog posts",
    backstory="You are an experienced content writer with expertise in various topics. You create compelling blog posts that engage readers and rank well in search engines.",
    llm=llm
)

blog_editor = Agent(
    role="Content Editor",
    goal="Improve and refine blog content",
    backstory="You are a meticulous editor with years of experience. You enhance clarity, fix grammar, and ensure content flows perfectly.",
    llm=llm
)

data_analyst = Agent(
    role="Data Analyst",
    goal="Analyze data and provide insights",
    backstory="You are a skilled data analyst who can extract meaningful patterns and insights from any dataset. You explain findings in simple, actionable terms.",
    llm=llm
)

insights_generator = Agent(
    role="Business Insights Specialist",
    goal="Generate actionable business insights",
    backstory="You take data analysis and convert it into strategic recommendations that businesses can implement.",
    llm=llm
)

code_reviewer = Agent(
    role="Senior Code Reviewer",
    goal="Review code for quality, security, and best practices",
    backstory="You are an expert programmer with deep knowledge of clean code principles, security best practices, and design patterns.",
    llm=llm
)

code_optimizer = Agent(
    role="Code Optimization Specialist",
    goal="Suggest performance improvements",
    backstory="You specialize in optimizing code for performance, readability, and maintainability.",
    llm=llm
)

# ============================================================
# ENDPOINTS
# ============================================================

@app.get("/", response_model=HealthResponse)
async def health_check():
    """
    Health check endpoint - verify API is running
    """
    return {
        "status": "healthy",
        "message": "CrewAI Agent API is running!",
        "timestamp": datetime.now().isoformat()
    }


@app.get("/docs", include_in_schema=False)
async def swagger_docs():
    """
    Swagger documentation
    Access at: http://localhost:8000/docs
    """
    pass


@app.post("/api/generate-blog", response_model=GenerateBlogResponse)
async def generate_blog(request: GenerateBlogRequest):
    """
    Generate a blog post on any topic
    
    Parameters:
    - topic: The topic for the blog post
    - length: "short" (~500 words), "medium" (~1000 words), "long" (~2000 words)
    
    Returns:
    - Blog post content
    - Status
    - Timestamp
    
    Example:
```json
    {
        "topic": "Artificial Intelligence in 2025",
        "length": "medium"
    }
```
    """
    
    try:
        # Adjust description based on length
        length_map = {
            "short": "Write a SHORT blog post (500 words)",
            "medium": "Write a MEDIUM blog post (1000 words)",
            "long": "Write a LONG blog post (2000 words)"
        }
        
        length_desc = length_map.get(request.length, length_map["medium"])
        
        # Create tasks
        write_task = Task(
            description=f"{length_desc} about: {request.topic}. Make it engaging and informative.",
            expected_output="Complete blog post draft",
            agent=blog_writer
        )
        
        edit_task = Task(
            description="Edit and improve the blog post. Fix grammar, improve clarity, enhance flow.",
            expected_output="Polished, publication-ready blog post",
            agent=blog_editor
        )
        
        # Create crew
        crew = Crew(agents=[blog_writer, blog_editor], tasks=[write_task, edit_task])
        
        # Execute
        result = crew.kickoff()
        
        return {
            "status": "success",
            "topic": request.topic,
            "blog_post": str(result),
            "generated_at": datetime.now().isoformat()
        }
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/analyze-data", response_model=AnalyzeDataResponse)
async def analyze_data(request: AnalyzeDataRequest):
    """
    Analyze data and provide insights
    
    Parameters:
    - data: The data to analyze (text format)
    - data_type: Type of data (sales, traffic, engagement, etc.)
    
    Returns:
    - Analysis
    - Key insights
    - Recommendations
    
    Example:
```json
    {
        "data": "Q1 sales: $500K, Q2: $650K, Q3: $800K, Q4: $950K",
        "data_type": "sales"
    }
```
    """
    
    try:
        # Create tasks
        analysis_task = Task(
            description=f"Analyze this {request.data_type} data and identify key patterns, trends, and anomalies: {request.data}",
            expected_output="Detailed analysis with findings",
            agent=data_analyst
        )
        
        insights_task = Task(
            description="Based on the analysis, generate 5 actionable business insights and recommendations",
            expected_output="List of 5 key insights with recommendations",
            agent=insights_generator
        )
        
        # Create crew
        crew = Crew(agents=[data_analyst, insights_generator], tasks=[analysis_task, insights_task])
        
        # Execute
        result = crew.kickoff()
        result_str = str(result)
        
        # Extract insights (simple parsing)
        insights = [
            line.strip() 
            for line in result_str.split('\n') 
            if line.strip() and any(keyword in line.lower() for keyword in ['insight', 'recommend', '-', '•'])
        ][:5]
        
        return {
            "status": "success",
            "analysis": result_str,
            "insights": insights if insights else ["See analysis for detailed insights"],
            "generated_at": datetime.now().isoformat()
        }
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/review-code", response_model=ReviewCodeResponse)
async def review_code(request: ReviewCodeRequest):
    """
    Review code for quality, security, and best practices
    
    Parameters:
    - code: The code to review
    - language: Programming language (python, javascript, java, etc.)
    
    Returns:
    - Code review
    - Issues found
    - Improvement suggestions
    
    Example:
```json
    {
        "code": "def add(a, b):\\n    return a + b",
        "language": "python"
    }
```
    """
    
    try:
        # Create tasks
        review_task = Task(
            description=f"Review this {request.language} code for quality, security, and best practices: {request.code}",
            expected_output="Detailed code review with issues and suggestions",
            agent=code_reviewer
        )
        
        optimize_task = Task(
            description="Suggest optimizations for performance, readability, and maintainability",
            expected_output="List of optimization suggestions",
            agent=code_optimizer
        )
        
        # Create crew
        crew = Crew(agents=[code_reviewer, code_optimizer], tasks=[review_task, optimize_task])
        
        # Execute
        result = crew.kickoff()
        result_str = str(result)
        
        # Count issues (simple heuristic)
        issues_found = result_str.count("issue") + result_str.count("problem") + result_str.count("bug")
        
        # Extract suggestions
        suggestions = [
            line.strip() 
            for line in result_str.split('\n') 
            if line.strip() and any(keyword in line.lower() for keyword in ['suggest', 'improve', '-', '•', 'use', 'add', 'remove'])
        ][:5]
        
        return {
            "status": "success",
            "review": result_str,
            "issues_found": max(issues_found, 1),
            "suggestions": suggestions if suggestions else ["See review for detailed suggestions"],
            "generated_at": datetime.now().isoformat()
        }
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# Additional endpoints for demonstration

@app.get("/api/status")
async def api_status():
    """Get API status and available endpoints"""
    return {
        "status": "operational",
        "version": "1.0.0",
        "endpoints": {
            "POST /api/generate-blog": "Generate blog posts",
            "POST /api/analyze-data": "Analyze data and get insights",
            "POST /api/review-code": "Review code for quality",
            "GET /api/status": "Get API status",
            "GET /docs": "Interactive API documentation"
        },
        "llm_model": "ollama/mistral",
        "timestamp": datetime.now().isoformat()
    }


@app.get("/api/examples")
async def get_examples():
    """Get example requests and responses"""
    return {
        "blog_example": {
            "request": {
                "topic": "Artificial Intelligence in 2025",
                "length": "medium"
            },
            "endpoint": "POST /api/generate-blog"
        },
        "data_example": {
            "request": {
                "data": "Q1: $500K, Q2: $650K, Q3: $800K, Q4: $950K",
                "data_type": "sales"
            },
            "endpoint": "POST /api/analyze-data"
        },
        "code_example": {
            "request": {
                "code": "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n-1)",
                "language": "python"
            },
            "endpoint": "POST /api/review-code"
        }
    }


# ============================================================
# ERROR HANDLERS
# ============================================================

@app.exception_handler(HTTPException)
async def http_exception_handler(request, exc):
    return {
        "status": "error",
        "message": exc.detail,
        "timestamp": datetime.now().isoformat()
    }


@app.exception_handler(Exception)
async def general_exception_handler(request, exc):
    return {
        "status": "error",
        "message": "Internal server error",
        "detail": str(exc),
        "timestamp": datetime.now().isoformat()
    }


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    print("\n" + "="*80)
    print("🚀 CREWAI AGENT API SERVER")
    print("="*80)
    print("\n📍 Server starting on: http://localhost:8000")
    print("📚 API Documentation: http://localhost:8000/docs")
    print("🔧 ReDoc: http://localhost:8000/redoc")
    print("\n" + "="*80)
    print("\nAvailable Endpoints:")
    print("  GET  /               - Health check")
    print("  GET  /api/status     - API status")
    print("  GET  /api/examples   - Example requests")
    print("  POST /api/generate-blog   - Generate blog posts")
    print("  POST /api/analyze-data    - Analyze data")
    print("  POST /api/review-code     - Review code")
    print("\n" + "="*80)
    print("\n💡 Test with curl:")
    print('curl -X POST "http://localhost:8000/api/generate-blog"')
    print('-H "Content-Type: application/json"')
    print('-d \'{"topic":"AI","length":"short"}\'')
    print("\n" + "="*80 + "\n")
    
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000,
        log_level="info"
    )