"""
Streamlit Dashboard for CrewAI Code Generator
Generated by: CrewAI Learning Archive
Date: June 12, 2026
Purpose: Beautiful UI for code generation and analysis
"""

import streamlit as st
from crewai import Agent, Task, Crew
from crewai.llm import LLM
from dotenv import load_dotenv
from datetime import datetime
import time

load_dotenv()

# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="🤖 CrewAI Code Generator",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main {
        padding: 0rem 0rem;
    }
    .stTabs [data-baseweb="tab-list"] button {
        font-size: 1.2em;
        padding: 1em;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================
# INITIALIZE LLM
# ============================================================

@st.cache_resource
def get_llm():
    return LLM(model="ollama/mistral", base_url="http://localhost:11434")

llm = get_llm()

# ============================================================
# AGENTS
# ============================================================

@st.cache_resource
def get_agents():
    architect = Agent(
        role="Software Architect",
        goal="Design optimal solutions for coding problems",
        backstory="You are an experienced architect who designs clean, scalable solutions",
        llm=llm
    )
    
    generator = Agent(
        role="Code Generator",
        goal="Write clean, production-ready code",
        backstory="You are an expert programmer who writes efficient, readable code",
        llm=llm
    )
    
    reviewer = Agent(
        role="Code Reviewer",
        goal="Review code for quality, security, and best practices",
        backstory="You are a meticulous code reviewer",
        llm=llm
    )
    
    debugger = Agent(
        role="Debugger",
        goal="Find and fix bugs in code",
        backstory="You are a master debugger",
        llm=llm
    )
    
    optimizer = Agent(
        role="Performance Optimizer",
        goal="Optimize code for speed and efficiency",
        backstory="You specialize in performance optimization",
        llm=llm
    )
    
    return architect, generator, reviewer, debugger, optimizer

# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:
    st.title("⚙️ Settings")
    st.markdown("---")
    
    model_choice = st.selectbox(
        "Select LLM Model",
        ["ollama/mistral", "ollama/neural-chat", "ollama/llama2"],
        help="Choose which local model to use"
    )
    
    st.markdown("---")
    st.subheader("📚 Quick Templates")
    
    templates = {
        "Factorial": "Create a function that calculates factorial with memoization",
        "Reverse String": "Build a function that reverses a string without using built-in reverse",
        "Prime Numbers": "Create a function that finds all prime numbers up to N",
        "Palindrome": "Write a function that checks if a string is a palindrome",
        "Binary Search": "Implement binary search algorithm with error handling",
        "Bubble Sort": "Create a sorting function with optimizations",
    }
    
    if st.button("📋 Show Templates"):
        st.info("**Click a template below to use it:**")
        for name, desc in templates.items():
            st.write(f"- **{name}**: {desc}")
    
    st.markdown("---")
    st.subheader("ℹ️ About")
    st.write("""
    This dashboard uses CrewAI with 5 specialized agents to:
    - Design optimal solutions
    - Generate production-ready code
    - Review code quality
    - Debug and test
    - Optimize performance
    """)

# ============================================================
# MAIN CONTENT
# ============================================================

# Header
st.markdown("""
<div style="text-align: center;">
    <h1>🤖 CrewAI Code Generator & Debugger</h1>
    <p style="font-size: 1.2em; color: gray;">
        Generate, Review, Debug, and Optimize Code Automatically
    </p>
</div>
""", unsafe_allow_html=True)

st.markdown("---")

# Tabs
tab1, tab2, tab3 = st.tabs(["💻 Generate Code", "📊 Code Analyzer", "📚 Documentation"])

# ============================================================
# TAB 1: GENERATE CODE
# ============================================================

with tab1:
    col1, col2 = st.columns([2, 1])
    
    with col1:
        st.subheader("📝 Enter Your Code Requirement")
        
        user_input = st.text_area(
            "What code do you want to generate?",
            placeholder="Example: Create a function that finds the longest word in a sentence",
            height=150,
            label_visibility="collapsed"
        )
    
    with col2:
        st.subheader("🎯 Quick Templates")
        
        selected_template = st.selectbox(
            "Or use a template:",
            ["Custom"] + list(templates.keys()),
            label_visibility="collapsed"
        )
        
        if selected_template != "Custom":
            user_input = templates[selected_template]
            st.info(f"✓ Template loaded: {selected_template}")
    
    st.markdown("---")
    
    # Generate button
    col1, col2, col3 = st.columns([1, 1, 2])
    
    with col1:
        generate_button = st.button("🚀 Generate Code", type="primary", use_container_width=True)
    
    with col2:
        clear_button = st.button("🗑️ Clear", use_container_width=True)
    
    if clear_button:
        st.rerun()
    
    if generate_button:
        if not user_input.strip():
            st.error("❌ Please enter a code requirement!")
        else:
            with st.spinner("🔄 Generating code... This may take 2-3 minutes"):
                progress_bar = st.progress(0)
                
                try:
                    architect, generator, reviewer, debugger, optimizer = get_agents()
                    
                    # Tasks
                    task_design = Task(
                        description=f"Design a solution for: {user_input}",
                        expected_output="Solution design with approach",
                        agent=architect
                    )
                    progress_bar.progress(20)
                    
                    task_generate = Task(
                        description=f"Write Python code for: {user_input}. Include docstrings, type hints, and error handling.",
                        expected_output="Complete, production-ready code",
                        agent=generator
                    )
                    progress_bar.progress(40)
                    
                    task_review = Task(
                        description="Review the generated code for quality, best practices, and security issues.",
                        expected_output="Code review with suggestions",
                        agent=reviewer
                    )
                    progress_bar.progress(60)
                    
                    task_debug = Task(
                        description="Test code with edge cases and find potential bugs.",
                        expected_output="Bug report with fixes",
                        agent=debugger
                    )
                    progress_bar.progress(80)
                    
                    task_optimize = Task(
                        description="Optimize code for performance and efficiency.",
                        expected_output="Optimized code with explanation",
                        agent=optimizer
                    )
                    progress_bar.progress(90)
                    
                    crew = Crew(agents=[architect, generator, reviewer, debugger, optimizer], tasks=[task_design, task_generate, task_review, task_debug, task_optimize])
                    
                    result = crew.kickoff()
                    progress_bar.progress(100)
                    
                    st.success("✅ Code Generated Successfully!")
                    
                    # Display results in tabs
                    st.markdown("---")
                    st.subheader("📊 Generated Code & Analysis")
                    
                    result_tabs = st.tabs(["📄 Full Result", "💾 Download"])
                    
                    with result_tabs[0]:
                        st.markdown(str(result))
                    
                    with result_tabs[1]:
                        st.download_button(
                            label="📥 Download Code as .txt",
                            data=str(result),
                            file_name=f"generated_code_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
                            mime="text/plain",
                            use_container_width=True
                        )
                        
                        st.download_button(
                            label="📥 Download Code as .py",
                            data=str(result),
                            file_name=f"generated_code_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py",
                            mime="text/plain",
                            use_container_width=True
                        )
                
                except Exception as e:
                    st.error(f"❌ Error generating code: {str(e)}")

# ============================================================
# TAB 2: CODE ANALYZER
# ============================================================

with tab2:
    st.subheader("🔍 Analyze Existing Code")
    
    code_to_analyze = st.text_area(
        "Paste code to analyze:",
        placeholder="Paste your Python code here...",
        height=200
    )
    
    col1, col2 = st.columns([1, 3])
    
    with col1:
        analyze_button = st.button("🔍 Analyze", type="primary", use_container_width=True)
    
    if analyze_button:
        if not code_to_analyze.strip():
            st.error("❌ Please paste code to analyze!")
        else:
            with st.spinner("Analyzing code..."):
                try:
                    _, _, reviewer, debugger, optimizer = get_agents()
                    
                    task_review = Task(
                        description=f"Review this Python code: {code_to_analyze}",
                        expected_output="Code review with issues and suggestions",
                        agent=reviewer
                    )
                    
                    task_debug = Task(
                        description="Find potential bugs and edge case issues.",
                        expected_output="Bug analysis",
                        agent=debugger
                    )
                    
                    task_optimize = Task(
                        description="Suggest performance optimizations.",
                        expected_output="Optimization suggestions",
                        agent=optimizer
                    )
                    
                    crew = Crew(agents=[reviewer, debugger, optimizer], tasks=[task_review, task_debug, task_optimize])
                    result = crew.kickoff()
                    
                    st.success("✅ Analysis Complete!")
                    st.markdown(str(result))
                
                except Exception as e:
                    st.error(f"❌ Error analyzing code: {str(e)}")

# ============================================================
# TAB 3: DOCUMENTATION
# ============================================================

with tab3:
    st.subheader("📚 How to Use This Dashboard")
    
    st.markdown("""
    ## 🎯 Getting Started
    
    ### 1. Generate Code
    - Enter a code requirement in plain English
    - Click "Generate Code"
    - Wait 2-3 minutes for analysis
    - Download the generated code
    
    ### 2. Analyze Code
    - Paste existing code
    - Click "Analyze"
    - Get review, bugs, and optimization suggestions
    
    ### 3. Use Templates
    - Select from quick templates in the sidebar
    - Auto-fills the requirement
    - Generate immediately
    
    ## 🤖 How the AI Works
    
    Your code goes through **5 AI agents**:
    
    1. **🏗️ Architect** - Designs optimal solution
    2. **💻 Code Generator** - Writes the code
    3. **👀 Code Reviewer** - Checks quality & best practices
    4. **🐛 Debugger** - Tests edge cases & finds bugs
    5. **⚡ Optimizer** - Improves performance
    
    ## ⚙️ Settings
    
    - **Model Selection**: Choose LLM (Mistral recommended)
    - **Templates**: Quick-start your code generation
    
    ## 📊 Example Results
    
    - **Factorial**: Optimized with memoization
    - **String Reversal**: 4 different algorithms compared
    - **Prime Numbers**: Sieve of Eratosthenes implementation
    
    ## 💡 Tips
    
    ✅ Be specific in your requirements
    ✅ Mention edge cases you care about
    ✅ Specify language (Python, JavaScript, etc.)
    ✅ Save generated code to files
    ✅ Test code locally before production
    
    ## ⏱️ Processing Time
    
    - **First call**: ~2-3 minutes (LLM thinking)
    - **Subsequent calls**: ~1-2 minutes (model warming up)
    - Local GPU: Much faster!
    """)
    
    st.markdown("---")
    
    st.subheader("🔗 Resources")
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        if st.button("📖 CrewAI Docs"):
            st.info("Visit: https://docs.crewai.com")
    
    with col2:
        if st.button("🤖 Ollama"):
            st.info("Visit: https://ollama.ai")
    
    with col3:
        if st.button("🚀 Streamlit"):
            st.info("Visit: https://streamlit.io")

# ============================================================
# FOOTER
# ============================================================

st.markdown("---")
st.markdown("""
<div style="text-align: center; color: gray; font-size: 0.9em;">
    <p>
        🤖 CrewAI Code Generator Dashboard | 
        🚀 Powered by Mistral AI | 
        ⚡ Optimized for Local Execution
    </p>
    <p>
        Built with ❤️ using CrewAI & Streamlit
    </p>
</div>
""", unsafe_allow_html=True)