"""
Code Generated: Reverse String Without Built-ins
Generated by: CrewAI 5-Agent Pipeline
Date: June 12, 2026
Agents: Architect → Generator → Reviewer → Debugger → Optimizer
"""

from typing import Union

# ============================================================
# OPTIMIZED STRING REVERSAL
# ============================================================

def reverse_string_slicing(input_str: str) -> str:
    """
    Reverse a string using Python slicing (most efficient).
    
    Args:
        input_str (str): The string to reverse
        
    Returns:
        str: The reversed string
        
    Raises:
        TypeError: If input is not a string
        
    Time Complexity: O(n)
    Space Complexity: O(n) - creates new string
    
    Example:
        >>> reverse_string_slicing("hello")
        'olleh'
        >>> reverse_string_slicing("Python")
        'nohtyP'
    """
    
    if not isinstance(input_str, str):
        raise TypeError(f"Expected str, got {type(input_str).__name__}")
    
    # Slicing with step -1 reverses the string
    return input_str[::-1]


def reverse_string_loop(input_str: str) -> str:
    """
    Reverse a string using a manual loop (educational).
    
    Args:
        input_str (str): The string to reverse
        
    Returns:
        str: The reversed string
        
    Raises:
        TypeError: If input is not a string
        
    Time Complexity: O(n)
    Space Complexity: O(n)
    
    Example:
        >>> reverse_string_loop("hello")
        'olleh'
    """
    
    if not isinstance(input_str, str):
        raise TypeError(f"Expected str, got {type(input_str).__name__}")
    
    reversed_str = ""
    for char in input_str:
        reversed_str = char + reversed_str
    
    return reversed_str


def reverse_string_stack(input_str: str) -> str:
    """
    Reverse a string using a stack data structure.
    
    Args:
        input_str (str): The string to reverse
        
    Returns:
        str: The reversed string
        
    Raises:
        TypeError: If input is not a string
        
    Time Complexity: O(n)
    Space Complexity: O(n)
    """
    
    if not isinstance(input_str, str):
        raise TypeError(f"Expected str, got {type(input_str).__name__}")
    
    stack = list(input_str)
    reversed_str = ""
    
    while stack:
        reversed_str += stack.pop()
    
    return reversed_str


def reverse_string_recursion(input_str: str) -> str:
    """
    Reverse a string using recursion.
    
    Args:
        input_str (str): The string to reverse
        
    Returns:
        str: The reversed string
        
    Raises:
        TypeError: If input is not a string
        RecursionError: If string is too long
        
    Time Complexity: O(n)
    Space Complexity: O(n) - call stack
    """
    
    if not isinstance(input_str, str):
        raise TypeError(f"Expected str, got {type(input_str).__name__}")
    
    if len(input_str) == 0:
        return ""
    
    return reverse_string_recursion(input_str[1:]) + input_str[0]


# ============================================================
# TESTING & EDGE CASES
# ============================================================

def test_reverse_string():
    """Test all string reversal methods"""
    
    test_cases = [
        ("", "", "Empty string"),
        ("a", "a", "Single character"),
        ("ab", "ba", "Two characters"),
        ("hello", "olleh", "Simple word"),
        ("Python", "nohtyP", "Word with capitals"),
        ("123", "321", "Numbers"),
        ("hello world!", "!dlrow olleh", "Sentence with punctuation"),
        ("a1b2c3", "3c2b1a", "Mixed alphanumeric"),
        ("  spaces  ", "  secaps  ", "String with spaces"),
    ]
    
    methods = [
        ("Slicing", reverse_string_slicing),
        ("Loop", reverse_string_loop),
        ("Stack", reverse_string_stack),
        ("Recursion", reverse_string_recursion),
    ]
    
    print("\n" + "="*80)
    print("STRING REVERSAL TESTS")
    print("="*80 + "\n")
    
    for method_name, method_func in methods:
        print(f"\n{method_name.upper()} METHOD:")
        print("-" * 40)
        
        for input_str, expected, description in test_cases:
            try:
                result = method_func(input_str)
                status = "✅" if result == expected else "❌"
                print(f"{status} {description}")
                print(f"   Input: '{input_str}' → Output: '{result}'")
            except Exception as e:
                print(f"❌ {description}")
                print(f"   Error: {type(e).__name__}: {str(e)}")
        
        print()


def test_error_handling():
    """Test error handling"""
    
    print("\n" + "="*80)
    print("ERROR HANDLING TESTS")
    print("="*80 + "\n")
    
    error_cases = [
        (123, TypeError, "Integer input"),
        (12.5, TypeError, "Float input"),
        (None, TypeError, "None input"),
        ([], TypeError, "List input"),
    ]
    
    for value, expected_error, description in error_cases:
        try:
            reverse_string_slicing(value)
            print(f"❌ {description} - Should raise {expected_error.__name__}")
        except expected_error:
            print(f"✅ {description} - Correctly raised {expected_error.__name__}")
        except Exception as e:
            print(f"❌ {description} - Wrong error: {type(e).__name__}")


# ============================================================
# PERFORMANCE COMPARISON
# ============================================================

def performance_test():
    """Compare performance of different methods"""
    
    import time
    
    print("\n" + "="*80)
    print("PERFORMANCE COMPARISON")
    print("="*80 + "\n")
    
    test_string = "a" * 10000  # 10,000 character string
    
    methods = [
        ("Slicing", reverse_string_slicing),
        ("Loop", reverse_string_loop),
        ("Stack", reverse_string_stack),
    ]
    
    print(f"String length: {len(test_string)} characters\n")
    
    for method_name, method_func in methods:
        start = time.time()
        for _ in range(100):
            method_func(test_string)
        elapsed = time.time() - start
        
        avg_time = elapsed / 100 * 1000  # Convert to milliseconds
        print(f"{method_name:15} | {avg_time:.4f}ms per call")
    
    print("\n⚡ SLICING is fastest!\n")


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    # Run tests
    test_reverse_string()
    
    # Error handling tests
    test_error_handling()
    
    # Performance tests
    performance_test()
    
    # Interactive usage
    print("\n" + "="*80)
    print("INTERACTIVE USAGE")
    print("="*80 + "\n")
    
    print("reverse_string_slicing('hello'):", reverse_string_slicing("hello"))
    print("reverse_string_slicing('Python'):", reverse_string_slicing("Python"))
    print("reverse_string_slicing('12345'):", reverse_string_slicing("12345"))