"""
Code Generated: Factorial with Memoization
Generated by: CrewAI 5-Agent Pipeline
Date: June 12, 2026
Agents: Architect → Generator → Reviewer → Debugger → Optimizer
"""

from functools import lru_cache
from typing import Union

# ============================================================
# OPTIMIZED FACTORIAL WITH MEMOIZATION
# ============================================================

@lru_cache(maxsize=None)
def factorial_memoized(n: int) -> int:
    """
    Calculate factorial of n using memoization for efficient caching.
    
    Args:
        n (int): Non-negative integer
        
    Returns:
        int: Factorial of n
        
    Raises:
        ValueError: If n is negative
        TypeError: If n is not an integer
        
    Time Complexity: O(n) for first call, O(1) for cached calls
    Space Complexity: O(n)
    
    Example:
        >>> factorial_memoized(5)
        120
        >>> factorial_memoized(0)
        1
    """
    
    # Input validation
    if not isinstance(n, int):
        raise TypeError(f"Expected int, got {type(n).__name__}")
    
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    
    # Base cases
    if n == 0 or n == 1:
        return 1
    
    # Recursive case with memoization (handled by @lru_cache)
    return n * factorial_memoized(n - 1)


# Alternative: Iterative approach (no recursion)
def factorial_iterative(n: int) -> int:
    """
    Calculate factorial using iteration (avoids recursion limit).
    
    Args:
        n (int): Non-negative integer
        
    Returns:
        int: Factorial of n
        
    Raises:
        ValueError: If n is negative
        TypeError: If n is not an integer
        
    Time Complexity: O(n)
    Space Complexity: O(1)
    """
    
    if not isinstance(n, int):
        raise TypeError(f"Expected int, got {type(n).__name__}")
    
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    
    result = 1
    for i in range(2, n + 1):
        result *= i
    
    return result


# ============================================================
# TESTING & EDGE CASES
# ============================================================

def test_factorial():
    """Test factorial function with edge cases"""
    
    test_cases = [
        (0, 1, "Zero factorial"),
        (1, 1, "One factorial"),
        (5, 120, "Five factorial"),
        (10, 3628800, "Ten factorial"),
    ]
    
    print("\n" + "="*80)
    print("FACTORIAL MEMOIZATION TESTS")
    print("="*80 + "\n")
    
    for n, expected, description in test_cases:
        try:
            result = factorial_memoized(n)
            status = "✅ PASS" if result == expected else "❌ FAIL"
            print(f"{status} | {description}")
            print(f"   Input: {n}, Expected: {expected}, Got: {result}\n")
        except Exception as e:
            print(f"❌ FAIL | {description}")
            print(f"   Error: {str(e)}\n")
    
    # Test error handling
    print("ERROR HANDLING TESTS:\n")
    
    error_cases = [
        (-5, ValueError, "Negative number"),
        ("5", TypeError, "String input"),
        (3.5, TypeError, "Float input"),
    ]
    
    for value, expected_error, description in error_cases:
        try:
            factorial_memoized(value)
            print(f"❌ FAIL | {description} - Should raise {expected_error.__name__}\n")
        except expected_error:
            print(f"✅ PASS | {description} - Correctly raised {expected_error.__name__}\n")
        except Exception as e:
            print(f"❌ FAIL | {description} - Wrong error: {type(e).__name__}\n")


# ============================================================
# PERFORMANCE COMPARISON
# ============================================================

def performance_test():
    """Compare memoized vs iterative approaches"""
    
    import time
    
    print("\n" + "="*80)
    print("PERFORMANCE COMPARISON")
    print("="*80 + "\n")
    
    n = 100
    
    # Clear cache for fair comparison
    factorial_memoized.cache_clear()
    
    # Test memoized (first call)
    start = time.time()
    result1 = factorial_memoized(n)
    time1 = time.time() - start
    
    # Test iterative
    start = time.time()
    result2 = factorial_iterative(n)
    time2 = time.time() - start
    
    # Test memoized (second call - should be cached)
    start = time.time()
    result3 = factorial_memoized(n)
    time3 = time.time() - start
    
    print(f"Input: {n}")
    print(f"Result: {result1}\n")
    
    print(f"Memoized (1st call): {time1:.6f}s")
    print(f"Iterative (1st call): {time2:.6f}s")
    print(f"Memoized (2nd call/cached): {time3:.6f}s\n")
    
    cache_info = factorial_memoized.cache_info()
    print(f"Cache Statistics:")
    print(f"  Hits: {cache_info.hits}")
    print(f"  Misses: {cache_info.misses}")
    print(f"  Hit Rate: {cache_info.hits / (cache_info.hits + cache_info.misses) * 100:.1f}%\n")


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    # Run tests
    test_factorial()
    
    # Run performance tests
    performance_test()
    
    # Interactive usage
    print("\n" + "="*80)
    print("INTERACTIVE USAGE")
    print("="*80 + "\n")
    
    print("Factorial of 5:", factorial_memoized(5))
    print("Factorial of 10:", factorial_memoized(10))
    print("Factorial of 20:", factorial_memoized(20))