"""
Code Generated: Find All Prime Numbers Up to N
Generated by: CrewAI 5-Agent Pipeline
Date: June 12, 2026
Agents: Architect → Generator → Reviewer → Debugger → Optimizer
"""

from typing import List
import time

# ============================================================
# SIEVE OF ERATOSTHENES (MOST EFFICIENT)
# ============================================================

def find_primes_sieve(n: int) -> List[int]:
    """
    Find all prime numbers up to n using Sieve of Eratosthenes.
    
    Args:
        n (int): Upper limit (inclusive)
        
    Returns:
        List[int]: Sorted list of all primes up to n
        
    Raises:
        ValueError: If n < 2
        TypeError: If n is not an integer
        
    Time Complexity: O(n log log n)
    Space Complexity: O(n)
    
    Example:
        >>> find_primes_sieve(10)
        [2, 3, 5, 7]
        >>> find_primes_sieve(30)
        [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
    """
    
    # Input validation
    if not isinstance(n, int):
        raise TypeError(f"Expected int, got {type(n).__name__}")
    
    if n < 2:
        raise ValueError("n must be greater than or equal to 2")
    
    # Create boolean array and initialize all as True
    is_prime = [True] * (n + 1)
    is_prime[0] = is_prime[1] = False  # 0 and 1 are not prime
    
    # Sieve algorithm
    limit_sqrt = int(n ** 0.5) + 1
    
    for p in range(2, limit_sqrt):
        if is_prime[p]:
            # Mark all multiples of p as not prime
            for multiple in range(p * p, n + 1, p):
                is_prime[multiple] = False
    
    # Collect all primes
    primes = [p for p in range(2, n + 1) if is_prime[p]]
    
    return primes


def find_primes_trial_division(n: int) -> List[int]:
    """
    Find all primes using trial division (simpler but slower).
    
    Args:
        n (int): Upper limit (inclusive)
        
    Returns:
        List[int]: Sorted list of all primes up to n
        
    Raises:
        ValueError: If n < 2
        TypeError: If n is not an integer
        
    Time Complexity: O(n * sqrt(n))
    Space Complexity: O(k) where k is number of primes
    """
    
    if not isinstance(n, int):
        raise TypeError(f"Expected int, got {type(n).__name__}")
    
    if n < 2:
        raise ValueError("n must be greater than or equal to 2")
    
    def is_prime(num: int) -> bool:
        """Check if a number is prime"""
        if num < 2:
            return False
        if num == 2:
            return True
        if num % 2 == 0:
            return False
        
        for i in range(3, int(num ** 0.5) + 1, 2):
            if num % i == 0:
                return False
        
        return True
    
    primes = [p for p in range(2, n + 1) if is_prime(p)]
    
    return primes


def find_primes_segmented_sieve(n: int) -> List[int]:
    """
    Find all primes using segmented sieve (for very large n).
    
    Args:
        n (int): Upper limit (inclusive)
        
    Returns:
        List[int]: Sorted list of all primes up to n
        
    Raises:
        ValueError: If n < 2
        TypeError: If n is not an integer
        
    Time Complexity: O(n log log n)
    Space Complexity: O(sqrt(n))
    """
    
    if not isinstance(n, int):
        raise TypeError(f"Expected int, got {type(n).__name__}")
    
    if n < 2:
        raise ValueError("n must be greater than or equal to 2")
    
    # Find all primes up to sqrt(n)
    limit = int(n ** 0.5) + 1
    is_prime_base = [True] * (limit + 1)
    is_prime_base[0] = is_prime_base[1] = False
    
    for p in range(2, limit + 1):
        if is_prime_base[p]:
            for multiple in range(p * p, limit + 1, p):
                is_prime_base[multiple] = False
    
    base_primes = [p for p in range(2, limit + 1) if is_prime_base[p]]
    
    if n < 2:
        return []
    
    if n < limit:
        return base_primes[:sum(1 for p in base_primes if p <= n)]
    
    # Collect all primes up to n
    all_primes = base_primes.copy()
    
    # Process segments
    low = limit
    high = min(low + limit, n + 1)
    
    while low <= n:
        high = min(low + limit, n + 1)
        is_prime_segment = [True] * (high - low)
        
        for p in base_primes:
            start = max(p * p, ((low + p - 1) // p) * p)
            
            for multiple in range(start, high, p):
                is_prime_segment[multiple - low] = False
        
        for i in range(high - low):
            if is_prime_segment[i]:
                all_primes.append(low + i)
        
        low = high
    
    return all_primes


# ============================================================
# TESTING & EDGE CASES
# ============================================================

def test_find_primes():
    """Test prime finding with various inputs"""
    
    test_cases = [
        (2, [2], "Smallest prime"),
        (10, [2, 3, 5, 7], "Primes up to 10"),
        (20, [2, 3, 5, 7, 11, 13, 17, 19], "Primes up to 20"),
        (30, [2, 3, 5, 7, 11, 13, 17, 19, 23, 29], "Primes up to 30"),
        (50, [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47], "Primes up to 50"),
    ]
    
    methods = [
        ("Sieve of Eratosthenes", find_primes_sieve),
        ("Trial Division", find_primes_trial_division),
    ]
    
    print("\n" + "="*80)
    print("PRIME NUMBER FINDING TESTS")
    print("="*80 + "\n")
    
    for method_name, method_func in methods:
        print(f"\n{method_name.upper()}:")
        print("-" * 40)
        
        for n, expected, description in test_cases:
            try:
                result = method_func(n)
                status = "✅" if result == expected else "❌"
                print(f"{status} {description}")
                print(f"   n={n}: {result}")
            except Exception as e:
                print(f"❌ {description}")
                print(f"   Error: {type(e).__name__}: {str(e)}")
        
        print()


def test_error_handling():
    """Test error handling"""
    
    print("\n" + "="*80)
    print("ERROR HANDLING TESTS")
    print("="*80 + "\n")
    
    error_cases = [
        (1, ValueError, "n=1 (below minimum)"),
        (0, ValueError, "n=0"),
        (-10, ValueError, "Negative n"),
        ("10", TypeError, "String input"),
        (10.5, TypeError, "Float input"),
    ]
    
    for value, expected_error, description in error_cases:
        try:
            find_primes_sieve(value)
            print(f"❌ {description} - Should raise {expected_error.__name__}")
        except expected_error:
            print(f"✅ {description} - Correctly raised {expected_error.__name__}")
        except Exception as e:
            print(f"❌ {description} - Wrong error: {type(e).__name__}")


def test_correctness():
    """Verify all methods produce same results"""
    
    print("\n" + "="*80)
    print("CORRECTNESS VERIFICATION")
    print("="*80 + "\n")
    
    test_values = [100, 500, 1000]
    
    for n in test_values:
        sieve_result = find_primes_sieve(n)
        trial_result = find_primes_trial_division(n)
        
        if sieve_result == trial_result:
            print(f"✅ n={n}: Both methods agree ({len(sieve_result)} primes found)")
        else:
            print(f"❌ n={n}: Methods disagree!")
            print(f"   Sieve: {len(sieve_result)} primes")
            print(f"   Trial: {len(trial_result)} primes")


# ============================================================
# PERFORMANCE COMPARISON
# ============================================================

def performance_test():
    """Compare performance of different methods"""
    
    print("\n" + "="*80)
    print("PERFORMANCE COMPARISON")
    print("="*80 + "\n")
    
    test_values = [100, 1000, 10000, 100000]
    
    print(f"{'n':>10} | {'Sieve':>12} | {'Trial Div':>12}")
    print("-" * 40)
    
    for n in test_values:
        # Sieve
        start = time.time()
        find_primes_sieve(n)
        sieve_time = (time.time() - start) * 1000
        
        # Trial division (skip for large n, too slow)
        if n <= 10000:
            start = time.time()
            find_primes_trial_division(n)
            trial_time = (time.time() - start) * 1000
        else:
            trial_time = float('inf')
        
        print(f"{n:>10} | {sieve_time:>10.3f}ms | {trial_time:>10.3f}ms")
    
    print("\n⚡ SIEVE OF ERATOSTHENES is fastest!\n")


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    # Run tests
    test_find_primes()
    
    # Error handling tests
    test_error_handling()
    
    # Correctness verification
    test_correctness()
    
    # Performance tests
    performance_test()
    
    # Interactive usage
    print("\n" + "="*80)
    print("INTERACTIVE USAGE")
    print("="*80 + "\n")
    
    print("Primes up to 20:", find_primes_sieve(20))
    print("Primes up to 50:", find_primes_sieve(50))
    print("Primes up to 100:", find_primes_sieve(100))
    print(f"\nTotal primes up to 100: {len(find_primes_sieve(100))}")